language: node_js
node_js: 8
addons:
  code_climate:
    repo_token: 97488220da208c44cbce579e30d33cdac571190d840163267a5e9c57d42d7c90
script: npm run test
before_script:
  - npm install
  - npm install -g codecov codeclimate-test-reporter
after_script:
  - codecov
  - codeclimate-test-reporter < ./coverage/lcov.info
deploy:
  provider: script
  skip_cleanup: true
  script:
    - npx semantic-release
